types: align with lib.dom.d.ts by removing [Symbol.toStringTag]
In TypeScript `lib.dom.d.ts`, the interfaces `File` and `FormData` do
not include the `[Symbol.toStringTag]` instance method.

By aligning types, can avoid type errors such as the following when
combining undici in a JSDom environment or other Browser like
environments.

```
.../tests/utils/fetch.ts:99:3 - error TS2322: Type 'Mock<(resource: RequestInfo | URL, options?: RequestInit | undefined) => Promise<Response>>' is not assignable to type '{ (input: RequestInfo | URL, init?: RequestInit | undefined): Promise<Response>; (input: string | Request | URL, init?: RequestInit | undefined): Promise<...>; }'.
  Types of parameters 'options' and 'init' are incompatible.
    Type 'RequestInit | undefined' is not assignable to type 'import(".../node_modules/undici/types/fetch").RequestInit | undefined'.
      Type 'RequestInit' is not assignable to type 'import(".../node_modules/undici/types/fetch").RequestInit'.
        Types of property 'body' are incompatible.
          Type 'BodyInit | null | undefined' is not assignable to type 'BodyInit | undefined'.
            Type 'FormData' is not assignable to type 'BodyInit | undefined'.
              Property '[Symbol.toStringTag]' is missing in type 'FormData' but required in type 'import(".../node_modules/undici/types/formdata").FormData'.

99   globalThis.fetch = jest.fn(fetch);
     ~~~~~~~~~~~~~~~~

  node_modules/undici/types/formdata.d.ts:107:12
    107   readonly [Symbol.toStringTag]: string
                   ~~~~~~~~~~~~~~~~~~~~
    '[Symbol.toStringTag]' is declared here.
```

```
.../tests/utils/fetch.ts:99:3 - error TS2322: Type 'Mock<(resource: URL | RequestInfo, options?: RequestInit | undefined) => Promise<Response>>' is not assignable to type '{ (input: URL | RequestInfo, init?: RequestInit | undefined): Promise<Response>; (input: string | URL | Request, init?: RequestInit | undefined): Promise<...>; }'.
  Types of parameters 'options' and 'init' are incompatible.
    Type 'RequestInit | undefined' is not assignable to type 'import(".../node_modules/undici/types/fetch").RequestInit | undefined'.
      Type 'RequestInit' is not assignable to type 'import(".../node_modules/undici/types/fetch").RequestInit'.
        Types of property 'body' are incompatible.
          Type 'BodyInit | null | undefined' is not assignable to type 'BodyInit | undefined'.
            Type 'FormData' is not assignable to type 'BodyInit | undefined'.
              Type 'FormData' is not assignable to type 'import(".../node_modules/undici/types/formdata").FormData'.
                The types returned by 'get(...)' are incompatible between these types.
                  Type 'FormDataEntryValue | null' is not assignable to type 'import(".../node_modules/undici/types/formdata").FormDataEntryValue | null'.
                    Type 'File' is not assignable to type 'FormDataEntryValue | null'.
                      Property '[Symbol.toStringTag]' is missing in type 'File' but required in type 'import(".../node_modules/undici/types/file").File'.

99   globalThis.fetch = jest.fn(fetch);
     ~~~~~~~~~~~~~~~~

  node_modules/undici/types/file.d.ts:38:12
    38   readonly [Symbol.toStringTag]: string
                  ~~~~~~~~~~~~~~~~~~~~
    '[Symbol.toStringTag]' is declared here.
```

These types were both originally added in
5425b77c503cb5af47419255778181c254f17089 adnd then modified slightly in
609d89b070f75d5f4d9f6d15f830f9cf4d3f6dfb.

The `[Symbol.toStringTag]` instance method is not something we expect
users to call directly.